final List<Map<String, String>> wordList = [
  {"word": "APPLE", "hint": "A sweet fruit that grows on trees."},
  {"word": "ELEPHANT", "hint": "The largest land animal with a trunk."},
  {"word": "SUNFLOWER", "hint": "A tall yellow flower that follows the sun."},
  {"word": "MOUNTAIN", "hint": "A high natural elevation of the land."},
  {"word": "RIVER", "hint": "A flowing body of water that leads to the sea."},
  {"word": "PYRAMID", "hint": "A triangular structure built in Egypt."},
  {"word": "KANGAROO", "hint": "A hopping marsupial from Australia."},
  {"word": "UMBRELLA", "hint": "Used to protect from rain or sun."},
  {"word": "PIANO", "hint": "A musical instrument with keys."},
  {"word": "TELESCOPE", "hint": "Used to see distant stars and planets."},
  {"word": "BICYCLE", "hint": "A two-wheeled vehicle you pedal."},
  {"word": "CANDLE", "hint": "Wax with a wick that provides light."},
  {"word": "HONEY", "hint": "Sweet substance made by bees."},
  {"word": "BUTTERFLY", "hint": "A colorful insect with wings."},
  {"word": "RAINBOW", "hint": "Colors that appear after rain."},
  {"word": "DIAMOND", "hint": "A precious and hard gemstone."},
  {"word": "GUITAR", "hint": "A string instrument you strum or pluck."},
  {"word": "BOOK", "hint": "Pages bound together for reading."},
  {"word": "CLOCK", "hint": "A device that shows time."},
  {"word": "OCEAN", "hint": "A vast body of saltwater."},
];